### ISSUE TITLE
OMW collection entry in the released index.toml has a bad key

### ISSUE THREAD

**Issue by goodmami** [omwn/omw-data#22]
The key for the index entry for OMW itself in the latest release is wrong:

```toml
[omw-1.4]
  label = "Open Multilingual Wordnet"
  language = "mul"
  license = "Please consult the LICENSE files included with the individual wordnets. Note that all permit redistribution."

  [omw-1.4.versions."1.4"]
    url = "https://github.com/bond-lab/omw-data/releases/download/v1.4/omw-1.4.tar.xz"
```

The key should just be `omw` without the version.
